# Generated by Django 4.0.5 on 2022-06-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_publicar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicar',
            name='imagen',
            field=models.ImageField(null=True, upload_to='publicar'),
        ),
    ]
