# Generated by Django 4.0.5 on 2022-06-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_publicar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicar',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
